/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangIndexRouteImport } from './routes/$lang/index'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as LangProjectsRouteImport } from './routes/$lang/projects'
import { Route as LangLoginRouteImport } from './routes/$lang/login'
import { Route as LangAboutRouteImport } from './routes/$lang/about'
import { Route as LangProtectedRouteRouteImport } from './routes/$lang/_protected/route'
import { Route as LangPostsIndexRouteImport } from './routes/$lang/posts/index'
import { Route as ApiWebhooksClerkRouteImport } from './routes/api/webhooks/clerk'
import { Route as LangPostsSlugRouteImport } from './routes/$lang/posts/$slug'
import { Route as LangProtectedNewRouteImport } from './routes/$lang/_protected/new'
import { Route as LangProtectedAdminRouteRouteImport } from './routes/$lang/_protected/admin/route'
import { Route as LangProtectedTranslatePostIdRouteImport } from './routes/$lang/_protected/translate/$postId'
import { Route as LangProtectedEditPostIdRouteImport } from './routes/$lang/_protected/edit/$postId'
import { Route as LangProtectedAdminQueueRouteImport } from './routes/$lang/_protected/admin/queue'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/$lang/',
  path: '/$lang/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const LangProjectsRoute = LangProjectsRouteImport.update({
  id: '/$lang/projects',
  path: '/$lang/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const LangLoginRoute = LangLoginRouteImport.update({
  id: '/$lang/login',
  path: '/$lang/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LangAboutRoute = LangAboutRouteImport.update({
  id: '/$lang/about',
  path: '/$lang/about',
  getParentRoute: () => rootRouteImport,
} as any)
const LangProtectedRouteRoute = LangProtectedRouteRouteImport.update({
  id: '/$lang/_protected',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const LangPostsIndexRoute = LangPostsIndexRouteImport.update({
  id: '/$lang/posts/',
  path: '/$lang/posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksClerkRoute = ApiWebhooksClerkRouteImport.update({
  id: '/api/webhooks/clerk',
  path: '/api/webhooks/clerk',
  getParentRoute: () => rootRouteImport,
} as any)
const LangPostsSlugRoute = LangPostsSlugRouteImport.update({
  id: '/$lang/posts/$slug',
  path: '/$lang/posts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LangProtectedNewRoute = LangProtectedNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => LangProtectedRouteRoute,
} as any)
const LangProtectedAdminRouteRoute = LangProtectedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LangProtectedRouteRoute,
} as any)
const LangProtectedTranslatePostIdRoute =
  LangProtectedTranslatePostIdRouteImport.update({
    id: '/translate/$postId',
    path: '/translate/$postId',
    getParentRoute: () => LangProtectedRouteRoute,
  } as any)
const LangProtectedEditPostIdRoute = LangProtectedEditPostIdRouteImport.update({
  id: '/edit/$postId',
  path: '/edit/$postId',
  getParentRoute: () => LangProtectedRouteRoute,
} as any)
const LangProtectedAdminQueueRoute = LangProtectedAdminQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => LangProtectedAdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangProtectedRouteRouteWithChildren
  '/$lang/about': typeof LangAboutRoute
  '/$lang/login': typeof LangLoginRoute
  '/$lang/projects': typeof LangProjectsRoute
  '/api/upload': typeof ApiUploadRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/admin': typeof LangProtectedAdminRouteRouteWithChildren
  '/$lang/new': typeof LangProtectedNewRoute
  '/$lang/posts/$slug': typeof LangPostsSlugRoute
  '/api/webhooks/clerk': typeof ApiWebhooksClerkRoute
  '/$lang/posts/': typeof LangPostsIndexRoute
  '/$lang/admin/queue': typeof LangProtectedAdminQueueRoute
  '/$lang/edit/$postId': typeof LangProtectedEditPostIdRoute
  '/$lang/translate/$postId': typeof LangProtectedTranslatePostIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$lang': typeof LangIndexRoute
  '/$lang/about': typeof LangAboutRoute
  '/$lang/login': typeof LangLoginRoute
  '/$lang/projects': typeof LangProjectsRoute
  '/api/upload': typeof ApiUploadRoute
  '/$lang/admin': typeof LangProtectedAdminRouteRouteWithChildren
  '/$lang/new': typeof LangProtectedNewRoute
  '/$lang/posts/$slug': typeof LangPostsSlugRoute
  '/api/webhooks/clerk': typeof ApiWebhooksClerkRoute
  '/$lang/posts': typeof LangPostsIndexRoute
  '/$lang/admin/queue': typeof LangProtectedAdminQueueRoute
  '/$lang/edit/$postId': typeof LangProtectedEditPostIdRoute
  '/$lang/translate/$postId': typeof LangProtectedTranslatePostIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang/_protected': typeof LangProtectedRouteRouteWithChildren
  '/$lang/about': typeof LangAboutRoute
  '/$lang/login': typeof LangLoginRoute
  '/$lang/projects': typeof LangProjectsRoute
  '/api/upload': typeof ApiUploadRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/_protected/admin': typeof LangProtectedAdminRouteRouteWithChildren
  '/$lang/_protected/new': typeof LangProtectedNewRoute
  '/$lang/posts/$slug': typeof LangPostsSlugRoute
  '/api/webhooks/clerk': typeof ApiWebhooksClerkRoute
  '/$lang/posts/': typeof LangPostsIndexRoute
  '/$lang/_protected/admin/queue': typeof LangProtectedAdminQueueRoute
  '/$lang/_protected/edit/$postId': typeof LangProtectedEditPostIdRoute
  '/$lang/_protected/translate/$postId': typeof LangProtectedTranslatePostIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/$lang/about'
    | '/$lang/login'
    | '/$lang/projects'
    | '/api/upload'
    | '/$lang/'
    | '/$lang/admin'
    | '/$lang/new'
    | '/$lang/posts/$slug'
    | '/api/webhooks/clerk'
    | '/$lang/posts/'
    | '/$lang/admin/queue'
    | '/$lang/edit/$postId'
    | '/$lang/translate/$postId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$lang'
    | '/$lang/about'
    | '/$lang/login'
    | '/$lang/projects'
    | '/api/upload'
    | '/$lang/admin'
    | '/$lang/new'
    | '/$lang/posts/$slug'
    | '/api/webhooks/clerk'
    | '/$lang/posts'
    | '/$lang/admin/queue'
    | '/$lang/edit/$postId'
    | '/$lang/translate/$postId'
  id:
    | '__root__'
    | '/'
    | '/$lang/_protected'
    | '/$lang/about'
    | '/$lang/login'
    | '/$lang/projects'
    | '/api/upload'
    | '/$lang/'
    | '/$lang/_protected/admin'
    | '/$lang/_protected/new'
    | '/$lang/posts/$slug'
    | '/api/webhooks/clerk'
    | '/$lang/posts/'
    | '/$lang/_protected/admin/queue'
    | '/$lang/_protected/edit/$postId'
    | '/$lang/_protected/translate/$postId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangProtectedRouteRoute: typeof LangProtectedRouteRouteWithChildren
  LangAboutRoute: typeof LangAboutRoute
  LangLoginRoute: typeof LangLoginRoute
  LangProjectsRoute: typeof LangProjectsRoute
  ApiUploadRoute: typeof ApiUploadRoute
  LangIndexRoute: typeof LangIndexRoute
  LangPostsSlugRoute: typeof LangPostsSlugRoute
  ApiWebhooksClerkRoute: typeof ApiWebhooksClerkRoute
  LangPostsIndexRoute: typeof LangPostsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/$lang'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/projects': {
      id: '/$lang/projects'
      path: '/$lang/projects'
      fullPath: '/$lang/projects'
      preLoaderRoute: typeof LangProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/login': {
      id: '/$lang/login'
      path: '/$lang/login'
      fullPath: '/$lang/login'
      preLoaderRoute: typeof LangLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/about': {
      id: '/$lang/about'
      path: '/$lang/about'
      fullPath: '/$lang/about'
      preLoaderRoute: typeof LangAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/_protected': {
      id: '/$lang/_protected'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/posts/': {
      id: '/$lang/posts/'
      path: '/$lang/posts'
      fullPath: '/$lang/posts/'
      preLoaderRoute: typeof LangPostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/clerk': {
      id: '/api/webhooks/clerk'
      path: '/api/webhooks/clerk'
      fullPath: '/api/webhooks/clerk'
      preLoaderRoute: typeof ApiWebhooksClerkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/posts/$slug': {
      id: '/$lang/posts/$slug'
      path: '/$lang/posts/$slug'
      fullPath: '/$lang/posts/$slug'
      preLoaderRoute: typeof LangPostsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/_protected/new': {
      id: '/$lang/_protected/new'
      path: '/new'
      fullPath: '/$lang/new'
      preLoaderRoute: typeof LangProtectedNewRouteImport
      parentRoute: typeof LangProtectedRouteRoute
    }
    '/$lang/_protected/admin': {
      id: '/$lang/_protected/admin'
      path: '/admin'
      fullPath: '/$lang/admin'
      preLoaderRoute: typeof LangProtectedAdminRouteRouteImport
      parentRoute: typeof LangProtectedRouteRoute
    }
    '/$lang/_protected/translate/$postId': {
      id: '/$lang/_protected/translate/$postId'
      path: '/translate/$postId'
      fullPath: '/$lang/translate/$postId'
      preLoaderRoute: typeof LangProtectedTranslatePostIdRouteImport
      parentRoute: typeof LangProtectedRouteRoute
    }
    '/$lang/_protected/edit/$postId': {
      id: '/$lang/_protected/edit/$postId'
      path: '/edit/$postId'
      fullPath: '/$lang/edit/$postId'
      preLoaderRoute: typeof LangProtectedEditPostIdRouteImport
      parentRoute: typeof LangProtectedRouteRoute
    }
    '/$lang/_protected/admin/queue': {
      id: '/$lang/_protected/admin/queue'
      path: '/queue'
      fullPath: '/$lang/admin/queue'
      preLoaderRoute: typeof LangProtectedAdminQueueRouteImport
      parentRoute: typeof LangProtectedAdminRouteRoute
    }
  }
}

interface LangProtectedAdminRouteRouteChildren {
  LangProtectedAdminQueueRoute: typeof LangProtectedAdminQueueRoute
}

const LangProtectedAdminRouteRouteChildren: LangProtectedAdminRouteRouteChildren =
  {
    LangProtectedAdminQueueRoute: LangProtectedAdminQueueRoute,
  }

const LangProtectedAdminRouteRouteWithChildren =
  LangProtectedAdminRouteRoute._addFileChildren(
    LangProtectedAdminRouteRouteChildren,
  )

interface LangProtectedRouteRouteChildren {
  LangProtectedAdminRouteRoute: typeof LangProtectedAdminRouteRouteWithChildren
  LangProtectedNewRoute: typeof LangProtectedNewRoute
  LangProtectedEditPostIdRoute: typeof LangProtectedEditPostIdRoute
  LangProtectedTranslatePostIdRoute: typeof LangProtectedTranslatePostIdRoute
}

const LangProtectedRouteRouteChildren: LangProtectedRouteRouteChildren = {
  LangProtectedAdminRouteRoute: LangProtectedAdminRouteRouteWithChildren,
  LangProtectedNewRoute: LangProtectedNewRoute,
  LangProtectedEditPostIdRoute: LangProtectedEditPostIdRoute,
  LangProtectedTranslatePostIdRoute: LangProtectedTranslatePostIdRoute,
}

const LangProtectedRouteRouteWithChildren =
  LangProtectedRouteRoute._addFileChildren(LangProtectedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangProtectedRouteRoute: LangProtectedRouteRouteWithChildren,
  LangAboutRoute: LangAboutRoute,
  LangLoginRoute: LangLoginRoute,
  LangProjectsRoute: LangProjectsRoute,
  ApiUploadRoute: ApiUploadRoute,
  LangIndexRoute: LangIndexRoute,
  LangPostsSlugRoute: LangPostsSlugRoute,
  ApiWebhooksClerkRoute: ApiWebhooksClerkRoute,
  LangPostsIndexRoute: LangPostsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
